comments/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import CommentCreateView

urlpatterns = [
    path('create/<str:content_type>/<int:object_id>/', CommentCreateView.as_view(), name='comment-create')
]

app_name = 'comments'

petSite/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include

from .views import PostListView, PostDetailView, Registr

urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<str:post_slug>', PostDetailView.as_view(), name='post'),
    path('registr/', Registr, name='registr'),
]

comments/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from utils.default_user import User


class Comment(models.Model):

    author = models.ForeignKey(User, verbose_name='Автор комментария', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    text = models.TextField(verbose_name='Текст комментария')
    created_at = models.DateTimeField(editable=False)

    def __str__(self):
        return f"{self.id}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        super().save(*args, **kwargs)

posts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from django.utils import timezone

from utils.default_user import User


class Post(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField()
    content = models.TextField(verbose_name='Содержимое поста')
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField()
    comments = GenericRelation('comments.Comment')

    def save(self, *args, **kwargs):

        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

comments/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']

posts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='This field is required')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2',)

comments/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import View

from .models import Comment
from .forms import CommentForm


class CommentCreateView(View):

    @staticmethod
    def post(request, *args, **kwargs):
        form = CommentForm(request.POST or None)
        ct = ContentType.objects.get(model=kwargs['content_type'])
        model = ct.model_class().objects.get(pk=kwargs['object_id'])
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.text = form.cleaned_data['text']
            new_comment.content_object = model
            new_comment.save()
            return HttpResponseRedirect(model.get_absolute_url())
        messages.add_message(request, messages.ERROR, 'Не удалось оставить комментарий')
        return HttpResponseRedirect(model.get_absolute_url())

posts/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView
from django.shortcuts import render

from .models import Post

from .forms import RegistrForm
from comments.forms import CommentForm


class PostListView(ListView):

    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):

    model = Post
    template_name = 'detail.html'
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm(self.request.POST or None)
        return context


# Функция регистрации
def Registr(request):
    data = {}
    if request.method == 'POST':
        form = RegistrForm(request.POST)
        if form.is_valid():
            form.save()
            data['form'] = form
            data['res'] = "Всё прошло успешно"

            return render(request, 'registration/registr.html', data)
    else:
        form = RegistrForm()
        data['form'] = form
        return render(request, 'registration/registr.html', data)

posts/templates/detail.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block title %} {{post.title}}{% endblock %}
{% block content %}

<div class="article_text">
    <hr>
    <h4 class="text-center">{{ post.title }}</h4>
    <small class="publication">Опубликовано: {{ post.created_at|date:"Y-m-d" }}</small>
    <br>
    <p>{{ post.content|linebreaksbr }}</p>
    <div class="trinker">
        <iframe src = "https://trinket.io/embed/python/f147c6cd00?toggleCode=true&runOption=run"
                width = "100%" height = "256" frameborder = "0"
                marginwidth = "0" marginheight = "0" allowfullscreen></iframe >
    </div>
    <hr>
    <p><strong>Комментарии</strong>: <span class="badge rounded-pill bg-dark">{{ post.comments.count }}</span></p>
    <br>
        {% for comment in post.comments.all %}
            <div class="col-md-12 mt-3 mb-3">
                <p><strong>{{ comment.author.username }}</strong> | <small>опубликовано:{{ comment.created_at|date:"Y-m-d" }}</small></p>
                <p>{{ comment.text }}</p>
            </div>
        {% endfor %}
    {% if request.user.is_authenticated %}
    <form action="{% url 'comments:comment-create' content_type='post' object_id=post.id %}"
          method="POST" class="form_com">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input class="btn btn-primary" type="submit" value="Отправить">
    </form>
    {% else %}
        <p class="text-center">Оставлять комментарии могут только авторизованные пользователи</p>
    {% endif %}
</div>
{% endblock content %}

posts/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Главная{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="./static/css/style.css" />
</head>

<body>
<header class="header">
    <div class="logo">
    <a href="{% url 'posts' %}">
        <span class="use">Тест</span> -<span class="web"> Сайт</span>
    </a>
    <p>Сайт на Python/Django</p>
</div>
<div class="top-menu">
    <ul>
        <li><a href="{% url 'posts' %}">Статьи</a></li>
        <li><a href="">Кнопка о нас</a></li>
        {% if user.is_authenticated %}
        <li><p class="login"><a href="{% url 'logout' %}">Выход</a></p></li>
            {% else %}
            <li class="login"><a href="{% url 'login' %}">Войти</a></li>
            <li class="login"><a href="{% url 'registr' %}">Регистрация</a></li>
        {% endif %}
    </ul>
</div>
</header>
{% block content %}
<h3>Статьи</h3>
<div class="menuTOP">
    {% for post in posts %}
        <div class="vertical-menu">
            <a href="{% url 'post' post_slug=post.slug %}" >
                <button class="btn ">{{ post.title }}</button>
            </a>
        </div>
    {% endfor %}
    <div class="home_text">
        <br>
        <p> Это заглушка сайта на Django 3</p>
        <img src="media/home.jpg" alt="Заглушка">
    </div>
</div>
{% endblock content %}
</body>
</html>